### ISSUE TITLE
Check security of installer

### ISSUE THREAD

**Issue by darobin** [w3c/echidna#110]
It is not immediately clear from reading the source of the installer (https://github.com/w3c/echidna/blob/master/lib/document-downloader.js#L53) that it will verify that paths in the manifest aren't something crazy like `../../../../../../etc/passwd`.

**Comment by astorije** [comment]
This should be inherently solved by #111, but I'll come up with a hacky patch to make sure you cannot use your example as a threat against me :D

**Comment by astorije** [comment]
@darobin, I need your 2 cents on this. Indeed, there is an issue with paths including `../`, but probably not what you'd expect.

Your example makes me believe that you meant: "make sure to not let the installer download a local system file and publish it on TR. Right? Well I don't believe this is possible, because [this part of the installer](https://github.com/w3c/echidna/blob/14f1d59fa46e39694e0d7a837b124febad62cc75/lib/document-downloader.js#L84) resolves paths with their original URL. Meaning that if you publish a manifest that lives at `https://example.com/foo/bar/MANIFEST` and that contains `file.html`, it will be resolved as `https://example.com/foo/bar/file.html`.

If I apply your example to the same URL, we get `../../../../../../etc/passwd` being resolved to `https://example.com/etc/passwd` because all `../` that are further than the root are simply ignored.

So as you see, one cannot access local system files or anything that is on the Echidna server (assuming that was your original bug report).
Now this also adds another issue. Say I have a token for `https://example.com/foo/bar/MANIFEST` but not for `https://example.com/imreally/reallybad/index.html`, I just need to mention `../../imreally/reallybad/index.html` in my manifest file and I can fool the system.
This is a real problem though (because we can now publish pretty much everything that is on GitHub :-)) and I am planning to simply forbid the usage of `../` in the manifest for now. Does that seem like a reasonable proposal to you?

**Comment by darobin** [comment]
Yes, this seems like a completely reasonable proposal, I don't think there's a good reason to support `../`

**Comment by tripu** [comment]
I can't think of a case for a legit `../` either.

**Comment by astorije** [comment]
Pfiou, I took my time, sorry... #184
