### ISSUE TITLE
Enable CORS for status and for POSTing

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#132]
Enabling CORS for the status reports would allow people to create their own UIs for checking the status of publication requests. 

Further, enabling CORS for posting would allow publication directly from an editor's draft with one click.... which is :star2:  "the dream" :star2:. 

cc @darobin

**Comment by tripu** [comment]
CORS is enabled since v1. See [`config.js.example#L19`](https://github.com/w3c/echidna/blob/master/config.js.example#L19) and [`app.js#L120`](https://github.com/w3c/echidna/blob/master/app.js#L120).

This exact same value of the variable `global.ALLOWED_CLIENTS` is the one that is deployed [in production](https://labs.w3.org/echidna/). As you can see, `Access-Control-Allow-*` headers are being sent only for a few domains initially:
* *localhost*
* W3C
* GitHub

Unless we see good reasons to enable CORS universally, for the time being I think it's safer for us to know exactly what those clients are.

@marcoscaceres, let us know if you want some specific domains to be added! (Here is a good place to do so.)

**Comment by darobin** [comment]
Quick question: what's the github one for? Right now it matches `github.com`, which means only stuff actually written by GitHub people (the company) can hit the API. Is that what was intended or am I missing something?

If the intent was to allow access from stuff we host on GitHub then it should match `github.io`, including a 3rd-level name. But if we allow *that* then it is not very different from allowing anyone :)

**Comment by astorije** [comment]
> including a 3rd-level name

What do you mean by this, @darobin?

**Comment by tripu** [comment]
I think @darobin means `*.github.io`&hellip;?

He's right in that allowing `github.com` won't do the trick here (requests will usually come from `*.github.io`).

We simply didn't think much about this yet. I added this basic support and a few initial examples with the idea that it'll be flexible enough to accommodate real necessities in the future. Right now, the regex in [`config.js.example#L19`](https://github.com/w3c/echidna/blob/master/config.js.example#L19) can be easily extended to include other patterns we may need. Of course, it won't look nice nor be maintainable if it grows past a certain point. If/when that happens, we should look into better mechanisms.

**Comment by astorije** [comment]
Right, of course :-)

I opened #144 to answer this. @darobin or @tripu, feel free to take the assignment.

**Comment by tripu** [comment]
:+1: @astorije

**Comment by marcoscaceres** [comment]
I'm happy with just using Travis for now. Thank you!
