### ISSUE TITLE
Publication failed because of a strange heuristic check in pubrules. :/

### ISSUE THREAD

**Issue by mikewest** [w3c/echidna#142]
https://lists.w3.org/Archives/Public/public-tr-notifications/2015Apr/0002.html failed because http://w3c.github.io/webappsec/specs/upgrade/published/WD.html contains a link with a series of numbers that the pubchecker doesn't like (https://labs.w3.org/pubrules/?url=http%3A%2F%2Fw3c.github.io%2Fwebappsec%2Fspecs%2Fupgrade%2Fpublished%2FWD.html&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004&processDocument=2014). I'd like to keep the link. :)

@darobin: Is this the right place to file this kind of bug?

**Comment by astorije** [comment]
Hi @mikewest,

Thanks for the report!
Actually, this issue is bound to [Specberus](https://github.com/w3c/specberus) but it was fair to report it here since you experienced it with Echidna. Feel free to report things here or there, no worries. I opened w3c/specberus#178 for that. I'll comment also here when we make progress on it.

In the meantime, could you please remove the `max-width` statement that creates these vertical margins around the document please? Documents should not vary in style from one version to another.
