### ISSUE TITLE
Support direct uploading of the TAR file?

### ISSUE THREAD

**Issue by tripu** [w3c/echidna#243]
Apparently there was [a misunderstanding](https://lists.w3.org/Archives/Public/spec-prod/2015OctDec/0080.html) when we discussed [support for TAR in Echidna](https://github.com/w3c/echidna/issues/230): @tabatkins and others were expecting that TAR file to be passed directly to the API, while we in the W3C team interpreted that the TAR file would available for downloading somewhere :(

Shall we extend the API so that users can send their manifest or TAR file directly to it?

In principle, I'm all for it. I'm asking here to get people to raise early objections related to security, and to discuss the best way to add that to the API.

**Comment by tabatkins** [comment]
Yeah, this really confused me - we were really explicit during the meeting that we wanted a way to send the files in the curl request, rather than indirecting through a webserver, and that's how tar came up - it was a "safe" well-known way to send a directory of files (rather than zip).  Being able to point to a tar on a webserver is just adding a step to the existing workflow - tarring the directory and uploading it, rather than just uploading the directory.
