### ISSUE TITLE
Provide an option to run Pubrules Checker on the generated document instead of the source one

### ISSUE THREAD

**Issue by siusin** [w3c/echidna#244]
In some cases editors would prefer to write a spec and its test suite at the same time, in the same file -- f.ex. <a href="https://w3c.github.io/clipboard-apis/">Clipboard APIs</a>. 

If the inline testing scripts aren't meant to be interpreted, the <a href="https://labs.w3.org/spec-generator/?type=respec&url=http%3A%2F%2Fw3c.github.io%2Fclipboard-apis%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dclipboard-apis">error messages</a> reported by ReSpec shouldn't block the publication as long as ReSpec is able to generate a correct document based on the source.

Is it possible to provide an option to check the generated file instead of the source in the manifest?

**Comment by deniak** [comment]
@siusin Echidna does check the generated file according to the [clipboard APIs manifest](https://github.com/w3c/clipboard-apis/blob/gh-pages/W3CTRMANIFEST).
Echidna is actually running specberus on the [link](https://labs.w3.org/spec-generator/?type=respec&url=http%3A%2F%2Fw3c.github.io%2Fclipboard-apis%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dclipboard-apis) you sent.
The problem is how respec handles the JS in that document, not echidna nor specberus.

**Comment by siusin** [comment]
@deniak Fair enough.
