### ISSUE TITLE
Make the token request form available to W3C Members

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#330]
Having to write an email to get the echidna token is a huge PITA. Firstly, you need to go and find who the team contact of a particular group is, then actually craft the email, and then wait maybe 12-24 hours. It would be great if the form that the W3C staff have access to already could be used to request the token.

**Comment by marcoscaceres** [comment]
I mean this form: https://www.w3.org/Web/publications/register

**Comment by tripu** [comment]
I understand the interest in removing obstacles, but I'm not sure that'd be a good idea.

Getting the token is done just once for every spec; it's not a repetitive task. Giving a token for any spec they want to any user of any member organisation as you suggest will be too risky, IMHO: the token works as a password, and it makes sense to communicate it to the editor(s) of the spec only.

**Comment by marcoscaceres** [comment]
oh, I wasn't suggesting that exactly: just a form the make the request quicly... basically the same info as would go in the email.

**Comment by tripu** [comment]
That would not save much time, I think. Users will have to fill in the URI or shortname of the spec they want a token for. They'd save only the time to scan the boilerplate looking for the team contact (but, since that should be *their* spec, they should already know who's their contact anyway), and the time required to write a couple of lines on an e-mail.
