### ISSUE TITLE
Allow sending encrypted un/pw to the TAR endpoint

### ISSUE THREAD

**Issue by tabatkins** [w3c/echidna#492]
Bikeshed currently talks to Echidna by sending a TAR file, authed by a W3C user's username and password.  This works fine locally, but if the group wants to allow publishing from their CI infrastructure, it requires revealing the un/pw to the CI.  Travis and other CIs have methods for storing "secrets" that aren't visible to the public, which is good, but not sufficient for this case - the secrets are still visible to anyone with admin rights to the repo, which means we'd be revealing our W3C password to our collaborators in the repo.

Instead, I'd like to just encrypt the username/password pair with a public key, which Echidna holds the private half of, and send that encrypted blob alongside the TAR, rather than doing HTTP auth.  The process would then be:

1. Locally, one of the editors asks Bikeshed to generate the auth token. It takes their username/password, and using its built-in public key, spits out some cyphertext.
2. The editor puts this string into the CI's secrets infrastructure.
3. The CI is then set up to hand Bikeshed the secret, which it sends to Echidna alongside the generated TAR.
4. Echidna uses its private key to decrypt the secret, and verifies that the username/password is correct, and that the username is allowed to publish for this spec (as it does today).
5. Profit.

This effectively bakes the user's credentials into a potentially-stealable token, but the stealing is limited to repo admins, which are already presumed trusted.  The token can't reveal the user's actual un/pw, just, at most, let someone else publish a spec from a repo that the token's user is already authorized to publish from.  (Using the *other* publication method, anyone with repo rights can publish already; this would allow exactly the same thing.)

**Comment by tabatkins** [comment]
So it's been almost three years, and there's still no way for Bikeshed to publish to Echidna without requiring username/password, and thus no way to auto-publish without revealing your W3C password to all of the admins of your repo.

Can we please either set up this infrastructure, or let me use a token with the TAR upload (like you can do with a URL), or *something* similar?

**Comment by deniak** [comment]
Sorry it's taking so long and thanks for the ping. The focus has shifted a bit because of lack of resources but that's something we should be able to fix after the process 2020 is deployed (mid September).

**Comment by deniak** [comment]
We finally gave some thoughts to the proposal above and it should indeed work fine. However, there are also some drawbacks:
- in the past, we received some comments about the complexity of setting up a CI to publish documents with Echidna. One of the steps that was a bit confusing for the users is the [token encryption](https://github.com/w3c/echidna/wiki/Setting-up-Echidna-as-a-GitHub-hook). If we were to ask people to import a public key to encrypt a set of credentials, this would probably add up to the current complexity.
- if the editor, that encrypted their username/password, changes their password, it will break the CI and the credentials will need to be encrypted again.

I discussed the issue with @vivienlacourba and we are thinking about changing the way we are using the tokens so they can be used in CI with both respec and bikeshed. 
At the moment, we aren't relying on the token only to trust a request as people, who know that token, could unwittingly share it to the public. So when checking the token, we are also making sure the document submitted comes from a trusted source. However, that method doesn't work with bikeshed as the document generated by bikeshed isn't directly accessible on the web and we don't know its source.

The idea is to trust all the requests as long as they have the right token associated with the specification. A set of trusted people will be in charge to generate/encrypt the token and configure the secret with the CI system chosen by the WG. This way only these trusted people will know the token and the editors will use the CI relying on that secret.
You mentioned that people with admin rights could decrypt the secrets but this doesn't seem to be the case with [travis](https://docs.travis-ci.com/user/encryption-keys/) or [github actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) (I'm not aware of groups using other CI systems).
We might also make sure the requests comes from a known IP of the CI Systems ([travis IP](https://docs.travis-ci.com/user/ip-addresses/) and [GitHub IP](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/about-githubs-ip-addresses)).

If we are going with that solution, people will no longer be able to manually trigger a request to Echidna with the token method (since they don't know it) but they can still use the credentials method.

//cc @plehegar and @dontcallmedom in case they have concerns with these changes

**Comment by dontcallmedom** [comment]
adding @sidvishnoi whose work on https://github.com/w3c/spec-prod (a github action to automate publication of TR documents) is highly relevant.

I wonder if Github Organizational Token might help here; part of what's unclear to me is if it would be OK that echidna be made to work only (or at least most easily) via github actions - this might simplify the problem space.

**Comment by tabatkins** [comment]
> in the past, we received some comments about the complexity of setting up a CI to publish documents with Echidna. One of the steps that was a bit confusing for the users is the token encryption. If we were to ask people to import a public key to encrypt a set of credentials, this would probably add up to the current complexity.

Note that "people" wouldn't have to do anything; this side would be handled by Bikeshed, which would just take in a un/pw and spit out an encrypted token.

> if the editor, that encrypted their username/password, changes their password, it will break the CI and the credentials will need to be encrypted again.

Yes, that would be the case in today's world as well, if the editor was putting their W3C un/pw into the CI's secrets infrastructure. In other words, no change from current.

> At the moment, we aren't relying on the token only to trust a request as people, who know that token, could unwittingly share it to the public.

Ah, right, I wasn't considering a token-reuse attack.

A potentially easier solution, since you already have the ability to check that a WG is publishing from a trusted repo:

* The WG puts a randomly-generated id-token in a well-known file in their repo (like `.w3c-ci-identifier` or something)
* The publishing-token Bikeshed generates contains the username, password, *and id-token*.
* The Echidna infrastructure fetches the well-known file from the appropriate repo and verifies that it matches what's in the publishing-token (along with verifying the un/pw of the user)

This way, if the publishing-token is leaked, the WG just has to change the id-token in their repo, and it'll automatically invalidate any publishing-tokens in the wild.

This gives you a bit of organizational trust, plus revocation, without needing to take on any secret-storage complexity on the W3C side, and still gives people a decent bit of freedom in how they want to handle their stuff.

**Comment by deniak** [comment]
> I wonder if Github Organizational Token might help here; part of what's unclear to me is if it would be OK that echidna be made to work only (or at least most easily) via github actions - this might simplify the problem space.

That would probably make things easier but it would be best if echidna could be agnostic and work with any CI tool. That being said, if there's a github action available, I'm guessing all the groups will use it.

**Comment by deniak** [comment]
> A potentially easier solution, since you already have the ability to check that a WG is publishing from a trusted repo:

Echidna actually doesn't know from which repo the request comes from. Even if the CI passes it as a parameter, Echidna cannot trust it as it can be easily updated in manual requests.

> 
>     * The WG puts a randomly-generated id-token in a well-known file in their repo (like `.w3c-ci-identifier` or something)
> 
>     * The publishing-token Bikeshed generates contains the username, password, _and id-token_.
> 
>     * The Echidna infrastructure fetches the well-known file from the appropriate repo and verifies that it matches what's in the publishing-token (along with verifying the un/pw of the user)
> 
> 
> This way, if the publishing-token is leaked, the WG just has to change the id-token in their repo, and it'll automatically invalidate any publishing-tokens in the wild.

Imo, the fact that it involves a user's credentials with the CI is an issue and we would also need a similar mechanism for respec.
Also, if a leaked publishing-token allows a publication from outside, we might very well use the token we have today, which can be invalidated and regenerated if it gets compromised.
Limiting the access to the token in clear to a set of trusted people should:

1. simplify the setup of the CI (although we still rely on these trusted people to configure the secret token, but the WG already needs the team contact to generate the token today)
2. avoid potential token leaks
3. the same method works with both bikeshed and respec

Note that the tar method will still work as it is today so that part wouldn't change for bikeshed but for the CI, we will need an option to specify the use of a token instead of the credentials.

> 
> This gives you a bit of organizational trust, plus revocation, without needing to take on any secret-storage complexity on the W3C side, and still gives people a decent bit of freedom in how they want to handle their stuff.

**Comment by vivienlacourba** [comment]
Let me state my support for @deniak above [revised proposal ](https://github.com/w3c/echidna/issues/492#issuecomment-706321372).

Basically 2 authentication mechanism would be provided for Echidna:
- one based on token that is recommended in a CI context (either via GitHub Actions or via Travis CI)
- one based on user credentials that will be suited for manually triggering a publication

With both methods be available with either Bikeshed or Respec.

We concluded that this was a good compromise between security, ease of use of echidna, and trying to stay agnostic with regards to the CI platform and the spec editing tool in use.

**Comment by deniak** [comment]
@tabatkins, it took quite a lot of time to fix but the update is finally deployed.
You should now be able to use the [token method](https://github.com/w3c/echidna/wiki/How-to-use-Echidna#tar-file) with a tar instead of using the W3C credentials. This will only work if the requests come from GH Actions or travis-ci though. Outside this context, you can still use the tar + W3C credentials as Bikeshed is doing today.

**Comment by tabatkins** [comment]
Heck yeah, thank you.
