### ISSUE TITLE
"start throwing publication requests at it"?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/echidna#88]
The README says:

"Then simply open http://localhost:3000 on your web browser and start throwing publication requests at it."

However, there is no way to do that from the web interface. That is quite confusing.

**Comment by tripu** [comment]
You're absolutely right. It's a remnant from the time when Echidna had a rudimentary web interface (that is now being developed [in a separate branch](https://github.com/w3c/echidna/tree/web-interface)).

[The fix is committed](https://github.com/w3c/echidna/commit/895ce6219787c96a56e72ceb957ce6ac0d303e1f), and it shall be merged very soon. Thanks!

**Comment by astorije** [comment]
Hey @tripu, sorry I stepped on your feet. I saw your commit after doing changes, just before committing :-/ I re-used your wording on #96.

I think this issue can be closed.
