### ISSUE TITLE
director approval

### ISSUE THREAD

**Issue by plehegar** [w3c/echidna#910]
https://github.com/w3c/echidna/blob/9b0689f52179d6e8cc320e3ddf3f767dc9f4161c/lib/transition-checker.js#L79

can we change that to detect this string anywhere in the comments? (you'll need to modify the comm to avoid confusion).

cc @swickr @koalie

**Comment by swickr** [comment]
Or at least anywhere before the first full stop ('.').

**Comment by koalie** [comment]
I don't understand anything of this issue, @plehegar /o\

**Comment by deniak** [comment]
> I don't understand anything of this issue, @plehegar /o\

In order to publish a CR Snapshot, Echidna needs to make sure the director has approved the transition and the Comm team has received the draft transition (e.g. https://github.com/w3c/transitions/issues/59#issuecomment-401446603 and https://github.com/w3c/transitions/issues/59#issuecomment-403376116) by looking at the GH comments *starting* with specific words.

If I recall correctly, we only look at the start of the comments to avoid edge cases where Echidna would consider the transition approved while it's not but I don't think we ever had such comments so I'm fine checking the string anywhere in the comment.
We could look for "draft transition approved." for the director and "draft transition received." for comm.

**Comment by koalie** [comment]
I defer to @deniak to ensure that the proposed change complies with Echidna CR Snapshot transition requirements. Thanks!

**Comment by jennyliang220** [comment]
> We could look for "draft transition approved." for the director and "draft transition received." for comm.

In PR #914, the wording for director remains to be `transition approved.` (cc @swickr ), 

while for the comm, the wording is changed into `draft transition received.` (cc @xueyuanjia and @koalie )

**Comment by xueyuanjia** [comment]
> while for the comm, the wording is changed into `draft transition received.`

For past CR publications by Echidna, do we need to trace them to reflect this change, e.g., replacing "draft transition approved" with "draft transition received", or additionally adding "draft transition received"?

When will this change take effect formally?

**Comment by jennyliang220** [comment]
> For past CR publications by Echidna, do we need to trace them to reflect this change, e.g., replacing "draft transition approved" with "draft transition received", or additionally adding "draft transition received"?

For `open` issues that will be checked by Echidna later, the wording needs to change. Left "draft transition approved" the way it is, and adding "draft transition received." to the comment is more secure. Both the current version and the new version of Echidna will take it.

> When will this change take effect formally?

Around next Monday, July 26th.
