### ISSUE TITLE
New FAQ entry: "Can I setup Echidna locally?"

### ISSUE THREAD

**Issue by anssiko** [w3c/echidna#94]
I was unable to push to the wiki directly (or fork it), so created this issue instead. I recommend adding the following [FAQ](https://github.com/w3c/echidna/wiki/FAQ) entry, or something along these lines:

[[

#### Can I setup Echidna locally?

Unfortunately not, since some of the system is linked to W3C's DB and the IPP system. We tried to expose as much as possible in the source code provided in GitHub. At the minimum, you should be able to run [Specberus](https://github.com/w3c/specberus) locally and probably the [`third-party-resources-checker`](https://github.com/dontcallmedom/third-party-resources-checker).

]]

**Comment by astorije** [comment]
Hey @anssiko, actually this is not completely true, at least for development purposes.

For example, the CVS integration interface is the same as a simple `cp` so that this step can be run locally without a CVS server. I might not have done a great job for all steps though, like providing a fake service that says "yes" all the time for interacting with the W3C DB. It is planned though.

You are right regarding Specberus and the Third Party Resources Checker, they both work standalone (the latter one, since recently, can be run as a binary or as a npm package.

If you meant running Echidna locally to actually publish documents, then no, it is not possible, and I don't see how it can be done easily with the current system.

@tripu, do you prefer to keep the wiki private?

**Comment by anssiko** [comment]
@astorije It'd be helpful if such a stub W3C DB interface would be provided for testing and development purposes. Is there an issue I should track, or should I open a new one?
 
The aim of the proposed FAQ entry was to clarify that if one sets up a local instance, one should not expect the full system to run out of the box without errors. The updated README https://github.com/w3c/echidna#how-to-get-it-up-and-running clarifies the expectations somewhat. The proposed FAQ entry provides complementary information. Feel free to modify it to better match reality :-)

**Comment by astorije** [comment]
@anssiko, it was on my todolist, but I am opening an issue right now for better transparency.

I suggested an edit to this wording, see #96. I am also interested if you think any unclear statements in this new README.

**Comment by anssiko** [comment]
Your following amendment looks good to me:
> but having mock services that emulate these pieces is our short-term goal.

Waiting for the emulation issue to track :-)

**Comment by astorije** [comment]
@anssiko, see #97 :-)

**Comment by anssiko** [comment]
@astorije awesome, thanks! Now you can link to the issue from the FAQ entry and/or the README if you wish to get more eyeballs :-)

**Comment by tripu** [comment]
The wiki was initially writable only by users with push access to the repo, but that was changed a while ago; now anyone can edit.

I added [your suggested copy, @anssiko, together with @astorije's comments and a reference to #97](https://github.com/w3c/echidna/wiki/FAQ#can-i-setup-echidna-locally). Thank you!

**Comment by anssiko** [comment]
Thanks to everyone who made Echidna more hackable!
